import json
import os
# pyrefly: ignore [missing-import]
from langchain_core.documents import Document
# pyrefly: ignore [missing-import]
from langchain_huggingface import HuggingFaceEmbeddings
# pyrefly: ignore [missing-import]
from langchain_community.vectorstores import FAISS

def build_vectorstore():
    # Read the structured data generated by the LLM analysis
    with open("analyzed_problems.json", "r", encoding="utf-8") as f:
        records = json.load(f)

    # Initialize our embedding model to convert text into mathematical vectors
    print("Loading embedding model...")
    embeddings = HuggingFaceEmbeddings(model_name="BAAI/bge-large-en-v1.5")

    # Package our analyzed data into searchable document objects
    documents = []
    print(f"Creating documents for {len(records)} records...")
    for record in records:
        # Skip any malformed records that don't have the dense semantic paragraph we need
        if not record.get("embedding_text"):
            continue

        page_content = record["embedding_text"]
        
        # Store just enough metadata for filtering, but strip the heavy text fields to keep the index lightning fast
        metadata = {
            k: v for k, v in record.items() 
            if k not in ["embedding_text", "my_solution_code"]
        }
        
        doc = Document(page_content=page_content, metadata=metadata)
        documents.append(doc)

    # Crunch all the embeddings into a highly optimized FAISS index
    print(f"Building FAISS vectorstore with {len(documents)} documents. This may take a moment...")
    vectorstore = FAISS.from_documents(documents, embeddings)

    # Persist the compiled vectorstore so we don't have to rebuild it every time
    output_dir = "faiss_index"
    vectorstore.save_local(output_dir)
    print(f"Vectorstore successfully saved to {output_dir}/")

    # Log the final count to confirm everything worked properly
    print(f"Total documents indexed: {len(documents)}")

if __name__ == "__main__":
    build_vectorstore()
