import os
import time
import json
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv

# pyrefly: ignore [missing-import]
from langchain_openai import ChatOpenAI
# pyrefly: ignore [missing-import]
from langchain_core.prompts import ChatPromptTemplate
# pyrefly: ignore [missing-import]
from openai import RateLimitError, APIError

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("Error: GROQ_API_KEY not found in .env")
    exit(1)

# Setup our smart assistants to generate hints and write code
hint_model = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
    temperature=0.3,
)

code_model = ChatOpenAI(
    model="openai/gpt-oss-120b",
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
    temperature=0.2,
)

# The specific instructions we feed the LLMs to keep them on track
HINT_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor helping a student solve a problem based on their past successful solutions. Your goal is to guide them toward the solution, not give it to them."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

Based on semantic retrieval, the student has solved similar problems in the past using the following techniques:
{past_patterns_context}

TASK:
1. Identify the most likely technique applicable here based on the trigger signals from the past problems.
2. Provide exactly ONE guiding question or observation that nudges the student toward this technique. 
3. DO NOT provide any code. DO NOT provide step-by-step pseudocode.
4. Do not just name the algorithm outright if you can avoid it — nudge them to realize it themselves based on the constraints or triggers.
5. IMPORTANT: When referring to past problems, use their actual names provided in the context (e.g., 'Two Sum') rather than vague terms like 'Past Problem 1'.
6. IMPORTANT: Output ONLY the actual hint or question directly! Do NOT include any meta-commentary like "Here is a guiding question:" or "Based on your past problems...".
""")
])

PSEUDOCODE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor helping a student solve a problem. You are given the optimal reference code for the problem. Your job is to write pseudocode for this exact approach."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

They asked for pseudocode. Based on semantic retrieval, the student has solved similar problems in the past using these techniques:
{past_patterns_context}

Here is the actual optimal reference code that will be shown to the student if they give up:
{reference_code}

TASK:
Provide logical, step-by-step pseudocode for the algorithm implemented in the reference code above. 
Do NOT write real programming language syntax. Keep it conceptual but detailed enough to implement. 
Ensure your pseudocode perfectly matches the logic of the reference code.
""")
])

CODE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor. The student is asking for a full reference solution based on their past coding style."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

Based on semantic retrieval, here are some past solutions they wrote for structurally similar problems:
{past_code_context}

TASK:
Provide a full, working solution for the new problem in the same programming language as the majority of their past solutions.

CRITICAL FORMATTING INSTRUCTIONS:
You must format your response as a clean, highly readable Markdown document for a student.
Use the following structure exactly:

### 🧠 Intuition & Approach
(Explain the algorithm conceptually in a way that is easy to understand. Keep it clear and concise.)

### ⏱️ Complexity
(Provide Time and Space complexity with a brief 1-sentence justification.)

### 💻 Reference Implementation
(Provide the code inside a standard markdown code block. Do not add any prefix comments like 'Generated by assistant'.)
""")
])

COACH_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming reasoning coach. The student is facing a problem that does not exactly match their past experience, but some loosely related past problems were retrieved. Your goal is to guide their reasoning process without giving away the full solution."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

These are the closest loosely related problems they have solved in the past:
{past_patterns_context}

TASK:
Act as a reasoning coach. Provide structured guidance based on constraints, algorithms, and invariants. Do not provide a full solution or code.

You MUST respond with ONLY valid JSON matching this exact structure:
{{
  "observations": ["observation 1", "observation 2"],
  "candidate_patterns": ["pattern 1", "pattern 2"],
  "invariants": ["invariant 1"],
  "edge_cases": ["edge case 1"],
  "questions_to_ask": ["question 1", "question 2"],
  "hint_1": "gentle nudge",
  "hint_2": "stronger nudge",
  "pitfalls": ["common pitfall"]
}}
""")
])

def _format_patterns_context(records: list[dict]) -> str:
    context_blocks = []
    for i, r in enumerate(records, 1):
        title = r.get('title_slug', f'Problem {i}').replace('-', ' ').title()
        context = f"--- Past Problem: '{title}' ---\n"
        context += f"Core Technique: {r.get('core_technique', '')}\n"
        context += f"Key Insight: {r.get('key_insight', '')}\n"
        context += f"Trigger Signals: {r.get('trigger_signals', '')}\n"
        context_blocks.append(context)
    return "\n".join(context_blocks)

def _format_code_context(records: list[dict]) -> str:
    context_blocks = []
    for i, r in enumerate(records, 1):
        context = f"--- Past Problem {i} ---\n"
        context += f"Core Technique: {r.get('core_technique', '')}\n"
        context += f"Solution Code:\n{r.get('my_solution_code', '')}\n"
        context_blocks.append(context)
    return "\n".join(context_blocks)

def generate_hint(problem_statement: str, retrieved_records: list[dict], stage: str = "hint", reference_code: str = "") -> str:
    """
    stage can be: 'hint', 'pseudocode', 'code'
    """
    if not retrieved_records and stage != "code":
        return (
            "I couldn't find any highly confident matches in your past solved problems. "
            "This might be a genuinely new pattern for you! Try rephrasing the problem description, "
            "or approach it from first principles."
        )

    if stage in ["hint", "pseudocode"]:
        prompt = HINT_PROMPT if stage == "hint" else PSEUDOCODE_PROMPT
        model = hint_model
        kwargs = {
            "problem_statement": problem_statement,
            "past_patterns_context": _format_patterns_context(retrieved_records)
        }
        if stage == "pseudocode":
            kwargs["reference_code"] = reference_code
    elif stage == "code":
        prompt = CODE_PROMPT
        model = code_model
        kwargs = {"problem_statement": problem_statement, "past_code_context": _format_code_context(retrieved_records)}
    else:
        raise ValueError("Invalid stage. Choose 'hint', 'pseudocode', or 'code'.")

    chain = prompt | model

    # Ping the API and gently back off if they ask us to slow down
    retries = 3
    while retries > 0:
        try:
            response = chain.invoke(kwargs)
            return response.content
        except RateLimitError as e:
            delay = 60.0
            print(f"[RateLimit] API rate limited. Waiting {delay:.0f}s before retrying...")
            time.sleep(delay)
            retries -= 1
        except APIError as e:
            print(f"[APIError] {e}")
            return f"Error connecting to API: {e}"
        except Exception as e:
            if "429" in str(e):
                delay = 60.0
                print(f"[RateLimit] Caught 429 inside general exception. Waiting {delay:.0f}s before retrying...")
                time.sleep(delay)
                retries -= 1
            else:
                print(f"[Error] {e}")
                return f"An unexpected error occurred: {e}"

    return "Failed to generate response after exhausting retries."


def generate_reasoning_coach(problem_statement: str, closest_results: list[dict]) -> dict:
    """
    Generates structured reasoning coach guidance as a dictionary.
    """
    chain = COACH_PROMPT | hint_model

    kwargs = {
        "problem_statement": problem_statement,
        "past_patterns_context": _format_patterns_context(closest_results)
    }

    retries = 3
    while retries > 0:
        try:
            response = chain.invoke(kwargs)
            content = response.content.strip()
            # Clean up the LLM's messy output in case it wrapped the JSON in markdown fences
            if content.startswith("```json"):
                content = content[7:]
            if content.startswith("```"):
                content = content[3:]
            if content.endswith("```"):
                content = content[:-3]
                
            return json.loads(content.strip())
        except json.JSONDecodeError as e:
            print(f"[JSONError] Failed to parse coach response: {e}")
            return {"error": "Failed to parse structured coach output.", "raw": response.content}
        except RateLimitError as e:
            delay = 60.0
            print(f"[RateLimit] API rate limited. Waiting {delay:.0f}s before retrying...")
            time.sleep(delay)
            retries -= 1
        except APIError as e:
            print(f"[APIError] {e}")
            return {"error": f"Error connecting to API: {e}"}
        except Exception as e:
            if "429" in str(e):
                delay = 60.0
                print(f"[RateLimit] Caught 429 inside general exception. Waiting {delay:.0f}s before retrying...")
                time.sleep(delay)
                retries -= 1
            else:
                print(f"[Error] {e}")
                return {"error": f"An unexpected error occurred: {e}"}

    return {"error": "Failed to generate coach response after exhausting retries."}


if __name__ == "__main__":
    from retrieve import retrieve_similar_problems
    
    # Test the script with a known query to ensure the LLMs are responding correctly
    test_problem = "find the kth largest element in an unsorted array."
    
    print("Testing retrieval gating and hint generation...")
    results = retrieve_similar_problems(test_problem, top_k_retrieve=15, top_k_final=5)
    
    if not results:
        print("\n--- GATED RESULT ---")
        print(generate_hint(test_problem, results, stage="hint"))
    else:
        print(f"\n--- HINT FOR '{test_problem[:50]}...' ---")
        hint = generate_hint(test_problem, results, stage="hint")
        print(hint)
