import os
import time
import json
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv

# pyrefly: ignore [missing-import]
from langchain_openai import ChatOpenAI
# pyrefly: ignore [missing-import]
from langchain_core.prompts import ChatPromptTemplate
# pyrefly: ignore [missing-import]
from openai import RateLimitError, APIError

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("Error: GROQ_API_KEY not found in .env")
    exit(1)

# Configures our two AI personas.
# One is a lightweight model for hints, the other is a heavy model for writing full code.
hint_model = ChatOpenAI(
    model="llama-3.3-70b-versatile",
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
    temperature=0.3,
    max_tokens=2048,
)

code_model = ChatOpenAI(
    model="openai/gpt-oss-120b",
    api_key=GROQ_API_KEY,
    base_url="https://api.groq.com/openai/v1",
    temperature=0.2,
    max_tokens=4096,
)

# The system prompts for our LLMs.
# These strict rules prevent the AI from blurting out the answer too early!
HINT_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor helping a student solve a new problem. Your goal is to guide them toward the solution with well-crafted hints, without giving away the full answer."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

(For your context: the student has solved these loosely related problems in the past, showing they might be familiar with these techniques:
{past_patterns_context})

TASK:
1. Identify the core algorithmic technique needed for the new problem.
2. Provide 2-3 bulleted hints or guiding questions focused ENTIRELY on the new problem's logic, constraints, and invariants.
3. DO NOT provide any code. DO NOT provide step-by-step pseudocode.
4. Do not just name the algorithm outright — nudge the student to realize it themselves based on the constraints.
5. CRITICAL: DO NOT explicitly name or reference the past problems in your output. Sometimes the retrieved past problems are only loosely related, and referencing them directly confuses the student. Keep the hints strictly about the new problem.
6. CRITICAL: Output ONLY the bulleted hints directly! Do NOT include any meta-commentary like "Here are some hints:" or "Based on your past work...".
""")
])

PSEUDOCODE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor helping a student solve a problem. You are given the optimal reference code for the problem. Your job is to write pseudocode for this exact approach."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

They asked for pseudocode. Based on semantic retrieval, the student has solved similar problems in the past using these techniques:
{past_patterns_context}

Here is the actual optimal reference code that will be shown to the student if they give up:
{reference_code}

TASK:
Provide logical, step-by-step pseudocode for the algorithm implemented in the reference code above. 
Do NOT write real programming language syntax. Keep it conceptual but detailed enough to implement. 
Ensure your pseudocode perfectly matches the logic of the reference code.
""")
])

CODE_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming mentor. The student is asking for a full reference solution based on their past coding style."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

Based on semantic retrieval, here are some past solutions they wrote for structurally similar problems:
{past_code_context}

TASK:
Provide a full, working solution for the new problem in the same programming language as the majority of their past solutions.

CRITICAL FORMATTING INSTRUCTIONS:
You must format your response as a clean, highly readable Markdown document for a student.
Use the following structure exactly:

### 🧠 Intuition & Approach
(Explain the algorithm conceptually in a way that is easy to understand. Keep it clear and concise.)

### ⏱️ Complexity
(Provide Time and Space complexity with a brief 1-sentence justification.)

### 💻 Reference Implementation
(Provide the code inside a standard markdown code block. Do not add any prefix comments like 'Generated by assistant'.)
""")
])

COACH_PROMPT = ChatPromptTemplate.from_messages([
    ("system", "You are an expert competitive programming reasoning coach. The student is facing a problem that does not exactly match their past experience, but some loosely related past problems were retrieved. Your goal is to guide their reasoning process without giving away the full solution."),
    ("user", """
The student is trying to solve this new problem:
{problem_statement}

These are the closest loosely related problems they have solved in the past:
{past_patterns_context}

TASK:
Act as a reasoning coach. Provide structured guidance based on constraints, algorithms, and invariants. Do not provide a full solution or code.

You MUST respond with ONLY valid JSON matching this exact structure:
{{
  "observations": ["observation 1", "observation 2"],
  "candidate_patterns": ["pattern 1", "pattern 2"],
  "invariants": ["invariant 1"],
  "edge_cases": ["edge case 1"],
  "questions_to_ask": ["question 1", "question 2"],
  "hint_1": "gentle nudge",
  "hint_2": "stronger nudge",
  "pitfalls": ["common pitfall"]
}}
""")
])

def _format_patterns_context(records: list[dict]) -> str:
    context_blocks = []
    for i, r in enumerate(records, 1):
        title = r.get('title_slug', f'Problem {i}').replace('-', ' ').title()
        context = f"--- Past Problem: '{title}' ---\n"
        context += f"Core Technique: {r.get('core_technique', '')}\n"
        context += f"Key Insight: {r.get('key_insight', '')}\n"
        context += f"Trigger Signals: {r.get('trigger_signals', '')}\n"
        context_blocks.append(context)
    return "\n".join(context_blocks)

def _format_code_context(records: list[dict]) -> str:
    context_blocks = []
    for i, r in enumerate(records, 1):
        context = f"--- Past Problem {i} ---\n"
        context += f"Core Technique: {r.get('core_technique', '')}\n"
        context += f"Solution Code:\n{r.get('my_solution_code', '')}\n"
        context_blocks.append(context)
    return "\n".join(context_blocks)

def generate_hint(problem_statement: str, retrieved_records: list[dict], stage: str = "hint", reference_code: str = "") -> str:
    # Routes the user's request to the correct LLM prompt.
    # We dynamically switch context based on which stage (hint, pseudocode, code) they are in.
    if not retrieved_records and stage != "code":
        return (
            "I couldn't find any highly confident matches in your past solved problems. "
            "This might be a genuinely new pattern for you! Try rephrasing the problem description, "
            "or approach it from first principles."
        )

    if stage in ["hint", "pseudocode"]:
        prompt = HINT_PROMPT if stage == "hint" else PSEUDOCODE_PROMPT
        model = hint_model
        kwargs = {
            "problem_statement": problem_statement,
            "past_patterns_context": _format_patterns_context(retrieved_records)
        }
        if stage == "pseudocode":
            kwargs["reference_code"] = reference_code
    elif stage == "code":
        prompt = CODE_PROMPT
        model = code_model
        kwargs = {"problem_statement": problem_statement, "past_code_context": _format_code_context(retrieved_records)}
    else:
        raise ValueError("Invalid stage. Choose 'hint', 'pseudocode', or 'code'.")

    chain = prompt | model

    # Fires the request to the Groq API.
    # Includes automatic retries just in case we hit rate limits.
    retries = 3
    while retries > 0:
        try:
            response = chain.invoke(kwargs)
            return response.content
        except RateLimitError as e:
            delay = 60.0
            print(f"[RateLimit] API rate limited. Waiting {delay:.0f}s before retrying...")
            time.sleep(delay)
            retries -= 1
        except APIError as e:
            print(f"[APIError] {e}")
            return f"Error connecting to API: {e}"
        except Exception as e:
            if "429" in str(e):
                delay = 60.0
                print(f"[RateLimit] Caught 429 inside general exception. Waiting {delay:.0f}s before retrying...")
                time.sleep(delay)
                retries -= 1
            else:
                print(f"[Error] {e}")
                return f"An unexpected error occurred: {e}"

    return "Failed to generate response after exhausting retries."


def generate_reasoning_coach(problem_statement: str, closest_results: list[dict]) -> dict:
    # Asks the AI to act as a reasoning coach.
    # It returns a strict JSON structure full of probing questions and edge cases.
    chain = COACH_PROMPT | hint_model

    kwargs = {
        "problem_statement": problem_statement,
        "past_patterns_context": _format_patterns_context(closest_results)
    }

    retries = 3
    while retries > 0:
        try:
            response = chain.invoke(kwargs)
            content = response.content.strip()
            # Strips markdown code fences from the AI's response.
            # Ensures we can cleanly parse the raw JSON data underneath.
            if content.startswith("```json"):
                content = content[7:]
            if content.startswith("```"):
                content = content[3:]
            if content.endswith("```"):
                content = content[:-3]
                
            return json.loads(content.strip())
        except json.JSONDecodeError as e:
            print(f"[JSONError] Failed to parse coach response: {e}")
            return {"error": "Failed to parse structured coach output.", "raw": response.content}
        except RateLimitError as e:
            delay = 60.0
            print(f"[RateLimit] API rate limited. Waiting {delay:.0f}s before retrying...")
            time.sleep(delay)
            retries -= 1
        except APIError as e:
            print(f"[APIError] {e}")
            return {"error": f"Error connecting to API: {e}"}
        except Exception as e:
            if "429" in str(e):
                delay = 60.0
                print(f"[RateLimit] Caught 429 inside general exception. Waiting {delay:.0f}s before retrying...")
                time.sleep(delay)
                retries -= 1
            else:
                print(f"[Error] {e}")
                return {"error": f"An unexpected error occurred: {e}"}

    return {"error": "Failed to generate coach response after exhausting retries."}
